[package]
name = "rmrk"
version = "0.1.0"

[addresses]
Std = "0x1"
Sender = "0x2"

[dependencies]
MoveStdlib = { local = "./move-stdlib", addr_subst = { "Std" = "0x1" } }
PontemFramework = { local = "./pontem-framework", addr_subst = { "Std" = "0x1" } }