[package]
name = "PontemFramework"
version = "0.0.0"

[addresses]
Std = "_"
DiemRoot = "0xA550C18"

[dev-addresses]
Std = "0x1"

[dependencies]
MoveStdlib = { local = "../move-stdlib", addr_subst = { "Std" = "0x1" } }